drop table if exists authority;
drop table if exists my_users;


CREATE TABLE IF NOT EXISTS my_users (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name  varchar(255) NOT NULL UNIQUE,
  email_id   varchar(255) NOT NULL UNIQUE,
  password   varchar(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS authority (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  varchar(255) NOT NULL UNIQUE,
  user_name   varchar(255) NOT NULL,
  constraint fk_user_auth foreign key(user_name)
    REFERENCES my_users(user_name) on delete restrict


);


