spring.application.name=boot-prometheus-grafana

server.port=8080
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.web.server.request.autotime.enabled=true


elasticsearch.host=localhost
elasticsearch.port=9200
