apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-deployment1
  namespace: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx # this im name it sholud match to slector app name
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
