apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector: # this is selector im name so kube could  understand wt group to replicate
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007 #this port
  type: NodePort

#